<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FeActividadEconomicasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fe_actividad_economicas')->insert([
            ['codigo' => '01111', 'valor' => 'Cultivo de cereales excepto arroz y para forrajes'],
            ['codigo' => '01112', 'valor' => 'Cultivo de legumbres'],
            ['codigo' => '01113', 'valor' => 'Cultivo de semillas oleaginosas'],
            ['codigo' => '01114', 'valor' => 'Cultivo de plantas para la preparación de semillas'],
            ['codigo' => '01119', 'valor' => 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.'],
            ['codigo' => '01120', 'valor' => 'Cultivo de arroz'],
            ['codigo' => '01131', 'valor' => 'Cultivo de raíces y tubérculos'],
            ['codigo' => '01132', 'valor' => 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares'],
            ['codigo' => '01133', 'valor' => 'Cultivo hortícola de fruto'],
            ['codigo' => '01134', 'valor' => 'Cultivo de hortalizas de hoja y otras hortalizas ncp'],
            ['codigo' => '01140', 'valor' => 'Cultivo de caña de azúcar'],
            ['codigo' => '01150', 'valor' => 'Cultivo de tabaco'],
            ['codigo' => '01161', 'valor' => 'Cultivo de algodón'],
            ['codigo' => '01162', 'valor' => 'Cultivo de fibras vegetales excepto algodón'],
            ['codigo' => '01191', 'valor' => 'Cultivo de plantas no perennes para la producción de semillas y flores'],
            ['codigo' => '01192', 'valor' => 'Cultivo de cereales y pastos para la alimentación animal'],
            ['codigo' => '01199', 'valor' => 'Producción de cultivos no estacionales ncp'],
            ['codigo' => '01220', 'valor' => 'Cultivo de frutas tropicales'],
            ['codigo' => '01230', 'valor' => 'Cultivo de cítricos'],
            ['codigo' => '01240', 'valor' => 'Cultivo de frutas de pepita y hueso'],
            ['codigo' => '01251', 'valor' => 'Cultivo de frutas ncp'],
            ['codigo' => '01252', 'valor' => 'Cultivo de otros frutos y nueces de árboles y arbustos'],
            ['codigo' => '01260', 'valor' => 'Cultivo de frutos oleaginosos'],
            ['codigo' => '01271', 'valor' => 'Cultivo de café'],
            ['codigo' => '01272', 'valor' => 'Cultivo de plantas para la elaboración de bebidas excepto café'],
            ['codigo' => '01281', 'valor' => 'Cultivo de especias y aromáticas'],
            ['codigo' => '01282', 'valor' => 'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos'],
            ['codigo' => '01291', 'valor' => 'Cultivo de árboles de hule (caucho) para la obtención de látex'],
            ['codigo' => '01292', 'valor' => 'Cultivo de plantas para la obtención de productos químicos y colorantes'],
            ['codigo' => '01299', 'valor' => 'Producción de cultivos perennes ncp'],
            ['codigo' => '01300', 'valor' => 'Propagación de plantas'],
            ['codigo' => '01301', 'valor' => 'Cultivo de plantas y flores ornamentales'],
            ['codigo' => '01410', 'valor' => 'Cría y engorde de ganado bovino'],
            ['codigo' => '01420', 'valor' => 'Cría de caballos y otros equinos'],
            ['codigo' => '01440', 'valor' => 'Cría de ovejas y cabras'],
            ['codigo' => '01450', 'valor' => 'Cría de cerdos'],
            ['codigo' => '01460', 'valor' => 'Cría de aves de corral y producción de huevos'],
            ['codigo' => '01491', 'valor' => 'Cría de abejas apicultura para la obtención de miel y otros productos apícolas'],
            ['codigo' => '01492', 'valor' => 'Cría de conejos'],
            ['codigo' => '01493', 'valor' => 'Cría de iguanas y garrobos'],
            ['codigo' => '01494', 'valor' => 'Cría de mariposas y otros insectos'],
            ['codigo' => '01499', 'valor' => 'Cría y obtención de productos animales n.c.p.'],
            ['codigo' => '01500', 'valor' => 'Cultivo de productos agrícolas en combinación con la cría de animales'],
            ['codigo' => '01611', 'valor' => 'Servicios de maquinaria agrícola'],
            ['codigo' => '01612', 'valor' => 'Control de plagas'],
            ['codigo' => '01613', 'valor' => 'Servicios de riego'],
            ['codigo' => '01614', 'valor' => 'Servicios de contratación de mano de obra para la agricultura'],
            ['codigo' => '01619', 'valor' => 'Servicios agrícolas ncp'],
            ['codigo' => '01621', 'valor' => 'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos'],
            ['codigo' => '01622', 'valor' => 'Servicios de mano de obra pecuaria'],
            ['codigo' => '01629', 'valor' => 'Servicios pecuarios ncp'],
            ['codigo' => '01631', 'valor' => 'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria'],
            ['codigo' => '01632', 'valor' => 'Servicio de beneficio de café'],
            ['codigo' => '01633', 'valor' => 'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)'],
            ['codigo' => '01640', 'valor' => 'Tratamiento de semillas para la propagación'],
            ['codigo' => '01700', 'valor' => 'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos'],
            ['codigo' => '02100', 'valor' => 'Silvicultura y otras actividades forestales'],
            ['codigo' => '02200', 'valor' => 'Extracción de madera'],
            ['codigo' => '02300', 'valor' => 'Recolección de productos diferentes a la madera'],
            ['codigo' => '02400', 'valor' => 'Servicios de apoyo a la silvicultura'],
            ['codigo' => '03110', 'valor' => 'Pesca marítima de altura y costera'],
            ['codigo' => '03120', 'valor' => 'Pesca de agua dulce'],
            ['codigo' => '03210', 'valor' => 'Acuicultura marítima'],
            ['codigo' => '03220', 'valor' => 'Acuicultura de agua dulce'],
            ['codigo' => '03300', 'valor' => 'Servicios de apoyo a la pesca y acuicultura'],
            ['codigo' => '05100', 'valor' => 'Extracción de hulla'],
            ['codigo' => '05200', 'valor' => 'Extracción y aglomeración de lignito'],
            ['codigo' => '06100', 'valor' => 'Extracción de petróleo crudo'],
            ['codigo' => '06200', 'valor' => 'Extracción de gas natural'],
            ['codigo' => '07100', 'valor' => 'Extracción de minerales de hierro'],
            ['codigo' => '07210', 'valor' => 'Extracción de minerales de uranio y torio'],
            ['codigo' => '07290', 'valor' => 'Extracción de minerales metalíferos no ferrosos'],
            ['codigo' => '08100', 'valor' => 'Extracción de piedra, arena y arcilla'],
            ['codigo' => '08910', 'valor' => 'Extracción de minerales para la fabricación de abonos y productos químicos'],
            ['codigo' => '08920', 'valor' => 'Extracción y aglomeración de turba'],
            ['codigo' => '08930', 'valor' => 'Extracción de sal'],
            ['codigo' => '08990', 'valor' => 'Explotación de otras minas y canteras ncp'],
            ['codigo' => '09100', 'valor' => 'Actividades de apoyo a la extracción de petróleo y gas natural'],
            ['codigo' => '09900', 'valor' => 'Actividades de apoyo a la explotación de minas y canteras'],
            ['codigo' => '10001', 'valor' => 'Empleados'],
            ['codigo' => '10002', 'valor' => 'Jubilado'],
            ['codigo' => '10003', 'valor' => 'Estudiante'],
            ['codigo' => '10004', 'valor' => 'Desempleado'],
            ['codigo' => '10005', 'valor' => 'Otros'],
            ['codigo' => '10101', 'valor' => 'Servicio de rastros y mataderos de bovinos y porcinos'],
            ['codigo' => '10102', 'valor' => 'Matanza y procesamiento de bovinos y porcinos'],
            ['codigo' => '10103', 'valor' => 'Matanza y procesamientos de aves de corral'],
            ['codigo' => '10104', 'valor' => 'Elaboración y conservación de embutidos y tripas naturales'],
            ['codigo' => '10105', 'valor' => 'Servicios de conservación y empaque de carnes'],
            ['codigo' => '10106', 'valor' => 'Elaboración y conservación de grasas y aceites animales'],
            ['codigo' => '10107', 'valor' => 'Servicios de molienda de carne'],
            ['codigo' => '10108', 'valor' => 'Elaboración de productos de carne ncp'],
            ['codigo' => '10201', 'valor' => 'Procesamiento y conservación de pescado, crustáceos y moluscos'],
            ['codigo' => '10209', 'valor' => 'Fabricación de productos de pescado ncp'],
            ['codigo' => '10301', 'valor' => 'Elaboración de jugos de frutas y hortalizas'],
            ['codigo' => '10302', 'valor' => 'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas'],
            ['codigo' => '10309', 'valor' => 'Elaboración de productos de frutas y hortalizas n.c.p.'],
            ['codigo' => '10401', 'valor' => 'Fabricación de aceites y grasas vegetales y animales comestibles'],
            ['codigo' => '10402', 'valor' => 'Fabricación de aceites y grasas vegetales y animales no comestibles'],
            ['codigo' => '10409', 'valor' => 'Servicio de maquilado de aceites'],
            ['codigo' => '10501', 'valor' => 'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos'],
            ['codigo' => '10502', 'valor' => 'Fabricación de sorbetes y helados'],
            ['codigo' => '10503', 'valor' => 'Fabricación de quesos'],
            ['codigo' => '10611', 'valor' => 'Molienda de cereales'],
            ['codigo' => '10612', 'valor' => 'Elaboración de cereales para el desayuno y similares'],
            ['codigo' => '10613', 'valor' => 'Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072 y beneficio de café rama 0163)'],
            ['codigo' => '10621', 'valor' => 'Fabricación de almidón'],
            ['codigo' => '10628', 'valor' => 'Servicio de molienda de maíz húmedo molino para nixtamal'],
            ['codigo' => '10711', 'valor' => 'Elaboración de tortillas'],
            ['codigo' => '10712', 'valor' => 'Fabricación de pan, galletas y barquillos'],
            ['codigo' => '10713', 'valor' => 'Fabricación de repostería'],
            ['codigo' => '10721', 'valor' => 'Ingenios azucareros'],
            ['codigo' => '10722', 'valor' => 'Molienda de caña de azúcar para la elaboración de dulces'],
            ['codigo' => '10723', 'valor' => 'Elaboración de jarabes de azúcar y otros similares'],
            ['codigo' => '10724', 'valor' => 'Maquilado de azúcar de caña'],
            ['codigo' => '10730', 'valor' => 'Fabricación de cacao, chocolates y productos de confitería'],
            ['codigo' => '10740', 'valor' => 'Elaboración de macarrones, fideos, y productos farináceos similares'],
            ['codigo' => '10750', 'valor' => 'Elaboración de comidas y platos preparados para la reventa en locales y/o para exportación'],
            ['codigo' => '10791', 'valor' => 'Elaboración de productos de café'],
            ['codigo' => '10792', 'valor' => 'Elaboración de especies, sazonadores y condimentos'],
            ['codigo' => '10793', 'valor' => 'Elaboración de sopas, cremas y consomé'],
            ['codigo' => '10794', 'valor' => 'Fabricación de bocadillos tostados y/o fritos'],
            ['codigo' => '10799', 'valor' => 'Elaboración de productos alimenticios ncp'],
            ['codigo' => '10800', 'valor' => 'Elaboración de alimentos preparados para animales'],
            ['codigo' => '11012', 'valor' => 'Fabricación de aguardiente y licores'],
            ['codigo' => '11020', 'valor' => 'Elaboración de vinos'],
            ['codigo' => '11030', 'valor' => 'Fabricación de cerveza'],
            ['codigo' => '11041', 'valor' => 'Fabricación de aguas gaseosas'],
            ['codigo' => '11042', 'valor' => 'Fabricación y envasado de agua'],
            ['codigo' => '11043', 'valor' => 'Elaboración de refrescos'],
            ['codigo' => '11048', 'valor' => 'Maquilado de aguas gaseosas'],
            ['codigo' => '11049', 'valor' => 'Elaboración de bebidas no alcohólicas'],
            ['codigo' => '12000', 'valor' => 'Elaboración de productos de tabaco'],
            ['codigo' => '13111', 'valor' => 'Preparación de fibras textiles'],
            ['codigo' => '13112', 'valor' => 'Fabricación de hilados'],
            ['codigo' => '13120', 'valor' => 'Fabricación de telas'],
            ['codigo' => '13130', 'valor' => 'Acabado de productos textiles'],
            ['codigo' => '13910', 'valor' => 'Fabricación de tejidos de punto y ganchillo'],
            ['codigo' => '13921', 'valor' => 'Fabricación de productos textiles para el hogar'],
            ['codigo' => '13922', 'valor' => 'Sacos, bolsas y otros artículos textiles'],
            ['codigo' => '13929', 'valor' => 'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir n.c.p'],
            ['codigo' => '13930', 'valor' => 'Fabricación de tapices y alfombras'],
            ['codigo' => '13941', 'valor' => 'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)'],
            ['codigo' => '13942', 'valor' => 'Fabricación de redes de diversos materiales'],
            ['codigo' => '13948', 'valor' => 'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)'],
            ['codigo' => '13991', 'valor' => 'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir'],
            ['codigo' => '13992', 'valor' => 'Servicio de bordados en artículos y prendas de tela'],
            ['codigo' => '13999', 'valor' => 'Fabricación de productos textiles ncp'],
            ['codigo' => '14101', 'valor' => 'Fabricación de ropa interior, para dormir y similares'],
            ['codigo' => '14102', 'valor' => 'Fabricación de ropa para niños'],
            ['codigo' => '14103', 'valor' => 'Fabricación de prendas de vestir para ambos sexos'],
            ['codigo' => '14104', 'valor' => 'Confección de prendas a medida'],
            ['codigo' => '14105', 'valor' => 'Fabricación de prendas de vestir para deportes'],
            ['codigo' => '14106', 'valor' => 'Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles'],
            ['codigo' => '14108', 'valor' => 'Maquilado de prendas de vestir, accesorios y otros'],
            ['codigo' => '14109', 'valor' => 'Fabricación de prendas y accesorios de vestir n.c.p.'],
            ['codigo' => '14200', 'valor' => 'Fabricación de artículos de piel'],
            ['codigo' => '14301', 'valor' => 'Fabricación de calcetines, calcetas, medias (panty house) y otros similares'],
            ['codigo' => '14302', 'valor' => 'Fabricación de ropa interior de tejido de punto'],
            ['codigo' => '14309', 'valor' => 'Fabricación de prendas de vestir de tejido de punto ncp'],
            ['codigo' => '15110', 'valor' => 'Curtido y adobo de cueros; adobo y teñido de pieles'],
            ['codigo' => '15121', 'valor' => 'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería'],
            ['codigo' => '15122', 'valor' => 'Fabricación de monturas, accesorios y vainas talabartería'],
            ['codigo' => '15123', 'valor' => 'Fabricación de artesanías principalmente de cuero natural y sintético'],
            ['codigo' => '15128', 'valor' => 'Maquilado de artículos de cuero natural, sintético y de otros materiales'],
            ['codigo' => '15201', 'valor' => 'Fabricación de calzado'],
            ['codigo' => '15202', 'valor' => 'Fabricación de partes y accesorios de calzado'],
            ['codigo' => '15208', 'valor' => 'Maquilado de partes y accesorios de calzado'],
            ['codigo' => '16100', 'valor' => 'Aserradero y acepilladura de madera'],
            ['codigo' => '16210', 'valor' => 'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción'],
            ['codigo' => '16220', 'valor' => 'Fabricación de partes y piezas de carpintería para edificios y construcciones'],
            ['codigo' => '16230', 'valor' => 'Fabricación de envases y recipientes de madera'],
            ['codigo' => '16292', 'valor' => 'Fabricación de artesanías de madera, semillas, materiales trenzables'],
            ['codigo' => '16299', 'valor' => 'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp'],
            ['codigo' => '17010', 'valor' => 'Fabricación de pasta de madera, papel y cartón'],
            ['codigo' => '17020', 'valor' => 'Fabricación de papel y cartón ondulado y envases de papel y cartón'],
            ['codigo' => '17091', 'valor' => 'Fabricación de artículos de papel y cartón de uso personal y doméstico'],
            ['codigo' => '17092', 'valor' => 'Fabricación de productos de papel ncp'],
            ['codigo' => '18110', 'valor' => 'Impresión'],
            ['codigo' => '18120', 'valor' => 'Servicios relacionados con la impresión'],
            ['codigo' => '18200', 'valor' => 'Reproducción de grabaciones'],
            ['codigo' => '19100', 'valor' => 'Fabricación de productos de hornos de coque'],
            ['codigo' => '19201', 'valor' => 'Fabricación de combustible'],
            ['codigo' => '19202', 'valor' => 'Fabricación de aceites y lubricantes'],
            ['codigo' => '20111', 'valor' => 'Fabricación de materias primas para la fabricación de colorantes'],
            ['codigo' => '20112', 'valor' => 'Fabricación de materiales curtientes'],
            ['codigo' => '20113', 'valor' => 'Fabricación de gases industriales'],
            ['codigo' => '20114', 'valor' => 'Fabricación de alcohol etílico'],
            ['codigo' => '20119', 'valor' => 'Fabricación de sustancias químicas básicas'],
            ['codigo' => '20120', 'valor' => 'Fabricación de abonos y fertilizantes'],
            ['codigo' => '20130', 'valor' => 'Fabricación de plástico y caucho en formas primarias'],
            ['codigo' => '20210', 'valor' => 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'],
            ['codigo' => '20220', 'valor' => 'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas'],
            ['codigo' => '20231', 'valor' => 'Fabricación de jabones, detergentes y similares para limpieza'],
            ['codigo' => '20232', 'valor' => 'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc.'],
            ['codigo' => '20291', 'valor' => 'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras'],
            ['codigo' => '20292', 'valor' => 'Fabricación de productos pirotécnicos, explosivos y municiones'],
            ['codigo' => '20299', 'valor' => 'Fabricación de productos químicos n.c.p.'],
            ['codigo' => '20300', 'valor' => 'Fabricación de fibras artificiales'],
            ['codigo' => '21001', 'valor' => 'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos'],
            ['codigo' => '21008', 'valor' => 'Maquilado de medicamentos'],
            ['codigo' => '22110', 'valor' => 'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas'],
            ['codigo' => '22190', 'valor' => 'Fabricación de otros productos de caucho'],
            ['codigo' => '22201', 'valor' => 'Fabricación de envases plásticos'],
            ['codigo' => '22202', 'valor' => 'Fabricación de productos plásticos para uso personal o doméstico'],
            ['codigo' => '22208', 'valor' => 'Maquila de plásticos'],
            ['codigo' => '22209', 'valor' => 'Fabricación de productos plásticos n.c.p.'],
            ['codigo' => '23101', 'valor' => 'Fabricación de vidrio'],
            ['codigo' => '23102', 'valor' => 'Fabricación de recipientes y envases de vidrio'],
            ['codigo' => '23108', 'valor' => 'Servicio de maquilado'],
            ['codigo' => '23109', 'valor' => 'Fabricación de productos de vidrio ncp'],
            ['codigo' => '23910', 'valor' => 'Fabricación de productos refractarios'],
            ['codigo' => '23920', 'valor' => 'Fabricación de productos de arcilla para la construcción'],
            ['codigo' => '23931', 'valor' => 'Fabricación de productos de cerámica y porcelana no refractaria'],
            ['codigo' => '23932', 'valor' => 'Fabricación de productos de cerámica y porcelana ncp'],
            ['codigo' => '23940', 'valor' => 'Fabricación de cemento, cal y yeso'],
            ['codigo' => '23950', 'valor' => 'Fabricación de artículos de hormigón, cemento y yeso'],
            ['codigo' => '23960', 'valor' => 'Corte, tallado y acabado de la piedra'],
            ['codigo' => '23990', 'valor' => 'Fabricación de productos minerales no metálicos ncp'],
            ['codigo' => '24100', 'valor' => 'Industrias básicas de hierro y acero'],
            ['codigo' => '24200', 'valor' => 'Fabricación de productos primarios de metales preciosos y metales no ferrosos'],
            ['codigo' => '24310', 'valor' => 'Fundición de hierro y acero'],
            ['codigo' => '24320', 'valor' => 'Fundición de metales no ferrosos'],
            ['codigo' => '25111', 'valor' => 'Fabricación de productos metálicos para uso estructural'],
            ['codigo' => '25118', 'valor' => 'Servicio de maquila para la fabricación de estructuras metálicas'],
            ['codigo' => '25120', 'valor' => 'Fabricación de tanques, depósitos y recipientes de metal'],
            ['codigo' => '25130', 'valor' => 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central'],
            ['codigo' => '25200', 'valor' => 'Fabricación de armas y municiones'],
            ['codigo' => '25910', 'valor' => 'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia'],
            ['codigo' => '25920', 'valor' => 'Tratamiento y revestimiento de metales'],
            ['codigo' => '25930', 'valor' => 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería'],
            ['codigo' => '25991', 'valor' => 'Fabricación de envases y artículos conexos de metal'],
            ['codigo' => '25992', 'valor' => 'Fabricación de artículos metálicos de uso personal y/o doméstico'],
            ['codigo' => '25999', 'valor' => 'Fabricación de productos elaborados de metal ncp'],
            ['codigo' => '26100', 'valor' => 'Fabricación de componentes electrónicos'],
            ['codigo' => '26200', 'valor' => 'Fabricación de computadoras y equipo conexo'],
            ['codigo' => '26300', 'valor' => 'Fabricación de equipo de comunicaciones'],
            ['codigo' => '26400', 'valor' => 'Fabricación de aparatos electrónicos de consumo para audio, video radio y televisión'],
            ['codigo' => '26510', 'valor' => 'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales'],
            ['codigo' => '26520', 'valor' => 'Fabricación de relojes y piezas de relojes'],
            ['codigo' => '26600', 'valor' => 'Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico'],
            ['codigo' => '26700', 'valor' => 'Fabricación de instrumentos de óptica y equipo fotográfico'],
            ['codigo' => '26800', 'valor' => 'Fabricación de medios magnéticos y ópticos'],
            ['codigo' => '27100', 'valor' => 'Fabricación de motores, generadores, transformadores eléctricos, aparatos de distribución y control de electricidad'],
            ['codigo' => '27200', 'valor' => 'Fabricación de pilas, baterías y acumuladores'],
            ['codigo' => '27310', 'valor' => 'Fabricación de cables de fibra óptica'],
            ['codigo' => '27320', 'valor' => 'Fabricación de otros hilos y cables eléctricos'],
            ['codigo' => '27330', 'valor' => 'Fabricación de dispositivos de cableados'],
            ['codigo' => '27400', 'valor' => 'Fabricación de equipo eléctrico de iluminación'],
            ['codigo' => '27500', 'valor' => 'Fabricación de aparatos de uso doméstico'],
            ['codigo' => '27900', 'valor' => 'Fabricación de otros tipos de equipo eléctrico'],
            ['codigo' => '28110', 'valor' => 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas'],
            ['codigo' => '28120', 'valor' => 'Fabricación de equipo hidráulico'],
            ['codigo' => '28130', 'valor' => 'Fabricación de otras bombas, compresores, grifos y válvulas'],
            ['codigo' => '28140', 'valor' => 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'],
            ['codigo' => '28150', 'valor' => 'Fabricación de hornos y quemadores'],
            ['codigo' => '28160', 'valor' => 'Fabricación de equipo de elevación y manipulación'],
            ['codigo' => '28170', 'valor' => 'Fabricación de maquinaria y equipo de oficina'],
            ['codigo' => '28180', 'valor' => 'Fabricación de herramientas manuales'],
            ['codigo' => '28190', 'valor' => 'Fabricación de otros tipos de maquinaria de uso general'],
            ['codigo' => '28210', 'valor' => 'Fabricación de maquinaria agropecuaria y forestal'],
            ['codigo' => '28220', 'valor' => 'Fabricación de máquinas para conformar metales y maquinaria herramienta'],
            ['codigo' => '28230', 'valor' => 'Fabricación de maquinaria metalúrgica'],
            ['codigo' => '28240', 'valor' => 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción'],
            ['codigo' => '28250', 'valor' => 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'],
            ['codigo' => '28260', 'valor' => 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros'],
            ['codigo' => '28291', 'valor' => 'Fabricación de máquinas para imprenta'],
            ['codigo' => '28299', 'valor' => 'Fabricación de maquinaria de uso especial ncp'],
            ['codigo' => '29100', 'valor' => 'Fabricación de vehículos automotores'],
            ['codigo' => '29200', 'valor' => 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques'],
            ['codigo' => '29300', 'valor' => 'Fabricación de partes, piezas y accesorios para vehículos automotores'],
            ['codigo' => '30110', 'valor' => 'Fabricación de buques'],
            ['codigo' => '30120', 'valor' => 'Construcción y reparación de embarcaciones de recreo'],
            ['codigo' => '30200', 'valor' => 'Fabricación de locomotoras y de material rodante'],
            ['codigo' => '30300', 'valor' => 'Fabricación de aeronaves y naves espaciales'],
            ['codigo' => '30400', 'valor' => 'Fabricación de vehículos militares de combate'],
            ['codigo' => '30910', 'valor' => 'Fabricación de motocicletas'],
            ['codigo' => '30920', 'valor' => 'Fabricación de bicicletas y sillones de ruedas para inválidos'],
            ['codigo' => '30990', 'valor' => 'Fabricación de equipo de transporte ncp'],
            ['codigo' => '31001', 'valor' => 'Fabricación de colchones y somier'],
            ['codigo' => '31002', 'valor' => 'Fabricación de muebles y otros productos de madera a medida'],
            ['codigo' => '31008', 'valor' => 'Servicios de maquilado de muebles'],
            ['codigo' => '31009', 'valor' => 'Fabricación de muebles ncp'],
            ['codigo' => '32110', 'valor' => 'Fabricación de joyas platerías y joyerías'],
            ['codigo' => '32120', 'valor' => 'Fabricación de joyas de imitación (fantasía) y artículos conexos'],
            ['codigo' => '32200', 'valor' => 'Fabricación de instrumentos musicales'],
            ['codigo' => '32301', 'valor' => 'Fabricación de artículos de deporte'],
            ['codigo' => '32308', 'valor' => 'Servicio de maquila de productos deportivos'],
            ['codigo' => '32401', 'valor' => 'Fabricación de juegos de mesa y de salón'],
            ['codigo' => '32402', 'valor' => 'Servicio de maquilado de juguetes y juegos'],
            ['codigo' => '32409', 'valor' => 'Fabricación de juegos y juguetes n.c.p.'],
            ['codigo' => '32500', 'valor' => 'Fabricación de instrumentos y materiales médicos y odontológicos'],
            ['codigo' => '32901', 'valor' => 'Fabricación de lápices, bolígrafos, sellos y artículos de librería en general'],
            ['codigo' => '32902', 'valor' => 'Fabricación de escobas, cepillos, pinceles y similares'],
            ['codigo' => '32903', 'valor' => 'Fabricación de artesanías de materiales diversos'],
            ['codigo' => '32904', 'valor' => 'Fabricación de artículos de uso personal y domésticos n.c.p.'],
            ['codigo' => '32905', 'valor' => 'Fabricación de accesorios para las confecciones y la marroquinería n.c.p.'],
            ['codigo' => '32908', 'valor' => 'Servicios de maquila ncp'],
            ['codigo' => '32909', 'valor' => 'Fabricación de productos manufacturados n.c.p.'],
            ['codigo' => '33110', 'valor' => 'Reparación y mantenimiento de productos elaborados de metal'],
            ['codigo' => '33120', 'valor' => 'Reparación y mantenimiento de maquinaria'],
            ['codigo' => '33130', 'valor' => 'Reparación y mantenimiento de equipo electrónico y óptico'],
            ['codigo' => '33140', 'valor' => 'Reparación y mantenimiento de equipo eléctrico'],
            ['codigo' => '33150', 'valor' => 'Reparación y mantenimiento de equipo de transporte, excepto vehículos automotores'],
            ['codigo' => '33190', 'valor' => 'Reparación y mantenimiento de equipos n.c.p.'],
            ['codigo' => '33200', 'valor' => 'Instalación de maquinaria y equipo industrial'],
            ['codigo' => '35101', 'valor' => 'Generación de energía eléctrica'],
            ['codigo' => '35102', 'valor' => 'Transmisión de energía eléctrica'],
            ['codigo' => '35103', 'valor' => 'Distribución de energía eléctrica'],
            ['codigo' => '35200', 'valor' => 'Fabricación de gas, distribución de combustibles gaseosos por tuberías'],
            ['codigo' => '35300', 'valor' => 'Suministro de vapor y agua caliente'],
            ['codigo' => '36000', 'valor' => 'Captación, tratamiento y suministro de agua'],
            ['codigo' => '37000', 'valor' => 'Evacuación de aguas residuales (alcantarillado)'],
            ['codigo' => '38110', 'valor' => 'Recolección y transporte de desechos sólidos proveniente de hogares y sector urbano'],
            ['codigo' => '38120', 'valor' => 'Recolección de desechos peligrosos'],
            ['codigo' => '38210', 'valor' => 'Tratamiento y eliminación de desechos inicuos'],
            ['codigo' => '38220', 'valor' => 'Tratamiento y eliminación de desechos peligrosos'],
            ['codigo' => '38301', 'valor' => 'Reciclaje de desperdicios y desechos textiles'],
            ['codigo' => '38302', 'valor' => 'Reciclaje de desperdicios y desechos de plástico y caucho'],
            ['codigo' => '38303', 'valor' => 'Reciclaje de desperdicios y desechos de vidrio'],
            ['codigo' => '38304', 'valor' => 'Reciclaje de desperdicios y desechos de papel y cartón'],
            ['codigo' => '38305', 'valor' => 'Reciclaje de desperdicios y desechos metálicos'],
            ['codigo' => '38309', 'valor' => 'Reciclaje de desperdicios y desechos no metálicos n.c.p.'],
            ['codigo' => '39000', 'valor' => 'Actividades de Saneamiento y otros Servicios de Gestión de Desechos'],
            ['codigo' => '41001', 'valor' => 'Construcción de edificios residenciales'],
            ['codigo' => '41002', 'valor' => 'Construcción de edificios no residenciales'],
            ['codigo' => '42100', 'valor' => 'Construcción de carreteras, calles y caminos'],
            ['codigo' => '42200', 'valor' => 'Construcción de proyectos de servicio público'],
            ['codigo' => '42900', 'valor' => 'Construcción de obras de ingeniería civil n.c.p.'],
            ['codigo' => '43110', 'valor' => 'Demolición'],
            ['codigo' => '43120', 'valor' => 'Preparación de terreno'],
            ['codigo' => '43210', 'valor' => 'Instalaciones eléctricas'],
            ['codigo' => '43220', 'valor' => 'Instalación de fontanería, calefacción y aire acondicionado'],
            ['codigo' => '43290', 'valor' => 'Otras instalaciones para obras de construcción'],
            ['codigo' => '43300', 'valor' => 'Terminación y acabado de edificios'],
            ['codigo' => '43900', 'valor' => 'Otras actividades especializadas de construcción'],
            ['codigo' => '43901', 'valor' => 'Fabricación de techos y materiales diversos'],
            ['codigo' => '45100', 'valor' => 'Venta de vehículos automotores'],
            ['codigo' => '45201', 'valor' => 'Reparación mecánica de vehículos automotores'],
            ['codigo' => '45202', 'valor' => 'Reparaciones eléctricas del automotor y recarga de baterías'],
            ['codigo' => '45203', 'valor' => 'Enderezado y pintura de vehículos automotores'],
            ['codigo' => '45204', 'valor' => 'Reparaciones de radiadores, escapes y silenciadores'],
            ['codigo' => '45205', 'valor' => 'Reparación y reconstrucción de vías, stop y otros artículos de fibra de vidrio'],
            ['codigo' => '45206', 'valor' => 'Reparación de llantas de vehículos automotores'],
            ['codigo' => '45207', 'valor' => 'Polarizado de vehículos (mediante la adhesión de papel especial a los vidrios)'],
            ['codigo' => '45208', 'valor' => 'Lavado y pasteado de vehículos (carwash)'],
            ['codigo' => '45209', 'valor' => 'Reparaciones de vehículos n.c.p.'],
            ['codigo' => '45211', 'valor' => 'Remolque de vehículos automotores'],
            ['codigo' => '45301', 'valor' => 'Venta de partes, piezas y accesorios nuevos para vehículos automotores'],
            ['codigo' => '45302', 'valor' => 'Venta de partes, piezas y accesorios usados para vehículos automotores'],
            ['codigo' => '45401', 'valor' => 'Venta de motocicletas'],
            ['codigo' => '45402', 'valor' => 'Venta de repuestos, piezas y accesorios de motocicletas'],
            ['codigo' => '45403', 'valor' => 'Mantenimiento y reparación de motocicletas'],
            ['codigo' => '46100', 'valor' => 'Venta al por mayor a cambio de retribución o por contrata'],
            ['codigo' => '46201', 'valor' => 'Venta al por mayor de materias primas agrícolas'],
            ['codigo' => '46202', 'valor' => 'Venta al por mayor de productos de la silvicultura'],
            ['codigo' => '46203', 'valor' => 'Venta al por mayor de productos pecuarios y de granja'],
            ['codigo' => '46211', 'valor' => 'Venta de productos para uso agropecuario'],
            ['codigo' => '46291', 'valor' => 'Venta al por mayor de granos básicos (cereales, leguminosas)'],
            ['codigo' => '46292', 'valor' => 'Venta al por mayor de semillas mejoradas para cultivo'],
            ['codigo' => '46293', 'valor' => 'Venta al por mayor de café oro y uva'],
            ['codigo' => '46294', 'valor' => 'Venta al por mayor de caña de azúcar'],
            ['codigo' => '46295', 'valor' => 'Venta al por mayor de flores, plantas y otros productos naturales'],
            ['codigo' => '46296', 'valor' => 'Venta al por mayor de productos agrícolas'],
            ['codigo' => '46297', 'valor' => 'Venta al por mayor de ganado bovino (vivo)'],
            ['codigo' => '46298', 'valor' => 'Venta al por mayor de animales porcinos, ovinos, caprino, canículas, apícolas, avícolas vivos'],
            ['codigo' => '46299', 'valor' => 'Venta de otras especies vivas del reino animal'],
            ['codigo' => '46301', 'valor' => 'Venta al por mayor de alimentos'],
            ['codigo' => '46302', 'valor' => 'Venta al por mayor de bebidas'],
            ['codigo' => '46303', 'valor' => 'Venta al por mayor de tabaco'],
            ['codigo' => '46371', 'valor' => 'Venta al por mayor de frutas, hortalizas (verduras), legumbres y tubérculos'],
            ['codigo' => '46372', 'valor' => 'Venta al por mayor de pollos, gallinas destazadas, pavos y otras aves'],
            ['codigo' => '46373', 'valor' => 'Venta al por mayor de carne bovina y porcina, productos de carne y embutidos'],
            ['codigo' => '46374', 'valor' => 'Venta al por mayor de huevos'],
            ['codigo' => '46375', 'valor' => 'Venta al por mayor de productos lácteos'],
            ['codigo' => '46376', 'valor' => 'Venta al por mayor de productos farináceos de panadería (pan dulce, cakes, respostería, etc.)'],
            ['codigo' => '46377', 'valor' => 'Venta al por mayor de pastas alimenticas, aceites y grasas comestibles vegetal y animal'],
            ['codigo' => '46378', 'valor' => 'Venta al por mayor de sal comestible'],
            ['codigo' => '46379', 'valor' => 'Venta al por mayor de azúcar'],
            ['codigo' => '46391', 'valor' => 'Venta al por mayor de abarrotes (vinos, licores, productos alimenticios envasados, etc.)'],
            ['codigo' => '46392', 'valor' => 'Venta al por mayor de aguas gaseosas'],
            ['codigo' => '46393', 'valor' => 'Venta al por mayor de agua purificada'],
            ['codigo' => '46394', 'valor' => 'Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo'],
            ['codigo' => '46395', 'valor' => 'Venta al por mayor de cerveza y licores'],
            ['codigo' => '46396', 'valor' => 'Venta al por mayor de hielo'],
            ['codigo' => '46411', 'valor' => 'Venta al por mayor de hilados, tejidos y productos textiles de mercería'],
            ['codigo' => '46412', 'valor' => 'Venta al por mayor de artículos textiles excepto confecciones para el hogar'],
            ['codigo' => '46413', 'valor' => 'Venta al por mayor de confecciones textiles para el hogar'],
            ['codigo' => '46414', 'valor' => 'Venta al por mayor de prendas de vestir y accesorios de vestir'],
            ['codigo' => '46415', 'valor' => 'Venta al por mayor de ropa usada'],
            ['codigo' => '46416', 'valor' => 'Venta al por mayor de calzado'],
            ['codigo' => '46417', 'valor' => 'Venta al por mayor de artículos de marroquinería y talabartería'],
            ['codigo' => '46418', 'valor' => 'Venta al por mayor de artículos de peletería'],
            ['codigo' => '46419', 'valor' => 'Venta al por mayor de otros artículos textiles n.c.p.'],
            ['codigo' => '46471', 'valor' => 'Venta al por mayor de instrumentos musicales'],
            ['codigo' => '46472', 'valor' => 'Venta al por mayor de colchones, almohadas, cojines, etc.'],
            ['codigo' => '46473', 'valor' => 'Venta al por mayor de artículos de aluminio para el hogar y para otros usos'],
            ['codigo' => '46474', 'valor' => 'Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax y no desechables'],
            ['codigo' => '46475', 'valor' => 'Venta al por mayor de cámaras fotográficas, accesorios y materiales'],
            ['codigo' => '46482', 'valor' => 'Venta al por mayor de medicamentos, artículos y otros productos de uso veterinario'],
            ['codigo' => '46483', 'valor' => 'Venta al por mayor de productos y artículos de belleza y de uso personal'],
            ['codigo' => '46484', 'valor' => 'Venta de produtos farmacéuticos y medicinales'],
            ['codigo' => '46491', 'valor' => 'Venta al por mayor de productos medicinales, cosméticos, perfumería y productos de limpieza'],
            ['codigo' => '46492', 'valor' => 'Venta al por mayor de relojes y artículos de joyería'],
            ['codigo' => '46493', 'valor' => 'Venta al por mayor de electrodomésticos y artículos del hogar excepto bazar; artículos de iluminación'],
            ['codigo' => '46494', 'valor' => 'Venta al por mayor de artículos de bazar y similares'],
            ['codigo' => '46495', 'valor' => 'Venta al por mayor de artículos de óptica'],
            ['codigo' => '46496', 'valor' => 'Venta al por mayor de revistas, periódicos, libros, artículos de librería y artículos de papel y cartón en general'],
            ['codigo' => '46497', 'valor' => 'Venta de artículos deportivos, juguetes y rodados'],
            ['codigo' => '46498', 'valor' => 'Venta al por mayor de productos usados para el hogar o el uso personal'],
            ['codigo' => '46499', 'valor' => 'Venta al por mayor de enseres domésticos y de uso personal n.c.p.'],
            ['codigo' => '46500', 'valor' => 'Venta al por mayor de bicicletas, partes, accesorios y otros'],
            ['codigo' => '46510', 'valor' => 'Venta al por mayor de computadoras, equipo periférico y programas informáticos'],
            ['codigo' => '46520', 'valor' => 'Venta al por mayor de equipos de comunicación'],
            ['codigo' => '46530', 'valor' => 'Venta al por mayor de maquinaria y equipo agropecuario, accesorios, partes y suministros'],
            ['codigo' => '46590', 'valor' => 'Venta de equipos e instrumentos de uso profesional y científico y aparatos de medida y control'],
            ['codigo' => '46591', 'valor' => 'Venta al por mayor de maquinaria equipo, accesorios y materiales para la industria de la madera y sus productos'],
            ['codigo' => '46592', 'valor' => 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria gráfica y del papel, cartón y productos de papel y cartón'],
            ['codigo' => '46593', 'valor' => 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria de productos químicos, plástico y caucho'],
            ['codigo' => '46594', 'valor' => 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria metálica y de sus productos'],
            ['codigo' => '46595', 'valor' => 'Venta al por mayor de equipamiento para uso médico, odontológico, veterinario y servicios conexos'],
            ['codigo' => '46596', 'valor' => 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria de la alimentación'],
            ['codigo' => '46597', 'valor' => 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria textil, confecciones y cuero'],
            ['codigo' => '46598', 'valor' => 'Venta al por mayor de maquinaria, equipo y accesorios para la construcción y explotación de minas y canteras'],
            ['codigo' => '46599', 'valor' => 'Venta al por mayor de otro tipo de maquinaria y equipo con sus accesorios y partes'],
            ['codigo' => '46610', 'valor' => 'Venta al por mayor de otros combustibles sólidos, líquidos, gaseosos y de productos conexos'],
            ['codigo' => '46612', 'valor' => 'Venta al por mayor de combustibles para automotores, aviones, barcos, maquinaria y otros'],
            ['codigo' => '46613', 'valor' => 'Venta al por mayor de lubricantes, grasas y otros aceites para automotores, maquinaria industrial, etc.'],
            ['codigo' => '46614', 'valor' => 'Venta al por mayor de gas propano'],
            ['codigo' => '46615', 'valor' => 'Venta al por mayor de leña y carbón'],
            ['codigo' => '46620', 'valor' => 'Venta al por mayor de metales y minerales metalíferos'],
            ['codigo' => '46631', 'valor' => 'Venta al por mayor de puertas, ventanas, vitrinas y similares'],
            ['codigo' => '46632', 'valor' => 'Venta al por mayor de artículos de ferretería y pinturerías'],
            ['codigo' => '46633', 'valor' => 'Vidrierías'],
            ['codigo' => '46634', 'valor' => 'Venta al por mayor de maderas'],
            ['codigo' => '46639', 'valor' => 'Venta al por mayor de materiales para la construcción n.c.p.'],
            ['codigo' => '46691', 'valor' => 'Venta al por mayor de sal industrial sin yodar'],
            ['codigo' => '46692', 'valor' => 'Venta al por mayor de productos intermedios y desechos de origen textil'],
            ['codigo' => '46693', 'valor' => 'Venta al por mayor de productos intermedios y desechos de origen metálico'],
            ['codigo' => '46694', 'valor' => 'Venta al por mayor de productos intermedios y desechos de papel y cartón'],
            ['codigo' => '46695', 'valor' => 'Venta al por mayor fertilizantes, abonos, agroquímicos y productos similares'],
            ['codigo' => '46696', 'valor' => 'Venta al por mayor de productos intermedios y desechos de origen plástico'],
            ['codigo' => '46697', 'valor' => 'Venta al por mayor de tintas para imprenta, productos curtientes y materias y productos colorantes'],
            ['codigo' => '46698', 'valor' => 'Venta de productos intermedios y desechos de origen químico y de caucho'],
            ['codigo' => '46699', 'valor' => 'Venta al por mayor de productos intermedios y desechos ncp'],
            ['codigo' => '46701', 'valor' => 'Venta de algodón en oro'],
            ['codigo' => '46900', 'valor' => 'Venta al por mayor de otros productos'],
            ['codigo' => '46901', 'valor' => 'Venta al por mayor de cohetes y otros productos pirotécnicos'],
            ['codigo' => '46902', 'valor' => 'Venta al por mayor de artículos diversos para consumo humano'],
            ['codigo' => '46903', 'valor' => 'Venta al por mayor de armas de fuego, municiones y accesorios'],
            ['codigo' => '46904', 'valor' => 'Venta al por mayor de toldos y tiendas de campaña de cualquier material'],
            ['codigo' => '46905', 'valor' => 'Venta al por mayor de exhibidores publicitarios y rótulos'],
            ['codigo' => '46906', 'valor' => 'Venta al por mayor de artículos promocionales diversos'],
            ['codigo' => '47111', 'valor' => 'Venta en supermercados'],
            ['codigo' => '47112', 'valor' => 'Venta en tiendas de artículos de primera necesidad'],
            ['codigo' => '47119', 'valor' => 'Almacenes (venta de diversos artículos)'],
            ['codigo' => '47190', 'valor' => 'Venta al por menor de otros productos en comercios no especializados'],
            ['codigo' => '47199', 'valor' => 'Venta de establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas y tabaco'],
            ['codigo' => '47211', 'valor' => 'Venta al por menor de frutas y hortalizas'],
            ['codigo' => '47212', 'valor' => 'Venta al por menor de carnes, embutidos y productos de granja'],
            ['codigo' => '47213', 'valor' => 'Venta al por menor de pescado y mariscos'],
            ['codigo' => '47214', 'valor' => 'Venta al por menor de productos lácteos'],
            ['codigo' => '47215', 'valor' => 'Venta al por menor de productos de panadería, repostería y galletas'],
            ['codigo' => '47216', 'valor' => 'Venta al por menor de huevos'],
            ['codigo' => '47217', 'valor' => 'Venta al por menor de carnes y productos cárnicos'],
            ['codigo' => '47218', 'valor' => 'Venta al por menor de granos básicos y otros'],
            ['codigo' => '47219', 'valor' => 'Venta al por menor de alimentos n.c.p.'],
            ['codigo' => '47221', 'valor' => 'Venta al por menor de hielo'],
            ['codigo' => '47223', 'valor' => 'Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento'],
            ['codigo' => '47224', 'valor' => 'Venta de bebidas alcohólicas, para su consumo fuera del establecimiento'],
            ['codigo' => '47225', 'valor' => 'Venta de bebidas alcohólicas para su consumo dentro del establecimiento'],
            ['codigo' => '47230', 'valor' => 'Venta al por menor de tabaco'],
            ['codigo' => '47300', 'valor' => 'Venta de combustibles, lubricantes y otros (gasolineras)'],
            ['codigo' => '47411', 'valor' => 'Venta al por menor de computadoras y equipo periférico'],
            ['codigo' => '47412', 'valor' => 'Venta de equipo y accesorios de telecomunicación'],
            ['codigo' => '47420', 'valor' => 'Venta al por menor de equipo de audio y video'],
            ['codigo' => '47510', 'valor' => 'Venta al por menor de hilados, tejidos y productos textiles de mercería; confecciones para el hogar y textiles n.c.p.'],
            ['codigo' => '47521', 'valor' => 'Venta al por menor de productos de madera'],
            ['codigo' => '47522', 'valor' => 'Venta al por menor de artículos de ferretería'],
            ['codigo' => '47523', 'valor' => 'Venta al por menor de productos de pinturerías'],
            ['codigo' => '47524', 'valor' => 'Venta al por menor en vidrierías'],
            ['codigo' => '47529', 'valor' => 'Venta al por menor de materiales de construcción y artículos conexos'],
            ['codigo' => '47530', 'valor' => 'Venta al por menor de tapices, alfombras y revestimientos de paredes y pisos en comercios especializados'],
            ['codigo' => '47591', 'valor' => 'Venta al por menor de muebles'],
            ['codigo' => '47592', 'valor' => 'Venta al por menor de artículos de bazar'],
            ['codigo' => '47593', 'valor' => 'Venta al por menor de aparatos electrodomésticos, repuestos y accesorios'],
            ['codigo' => '47594', 'valor' => 'Venta al por menor de artículos eléctricos y de iluminación'],
            ['codigo' => '47598', 'valor' => 'Venta al por menor de instrumentos musicales'],
            ['codigo' => '47610', 'valor' => 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados'],
            ['codigo' => '47620', 'valor' => 'Venta al por menor de discos láser, cassettes, cintas de video y otros'],
            ['codigo' => '47630', 'valor' => 'Venta al por menor de productos y equipos de deporte'],
            ['codigo' => '47631', 'valor' => 'Venta al por menor de bicicletas, accesorios y repuestos'],
            ['codigo' => '47640', 'valor' => 'Venta al por menor de juegos y juguetes en comercios especializados'],
            ['codigo' => '47711', 'valor' => 'Venta al por menor de prendas de vestir y accesorios de vestir'],
            ['codigo' => '47712', 'valor' => 'Venta al por menor de calzado'],
            ['codigo' => '47713', 'valor' => 'Venta al por menor de artículos de peletería, marroquinería y talabartería'],
            ['codigo' => '47721', 'valor' => 'Venta al por menor de medicamentos farmacéuticos y otros materiales y artículos de uso médico, odontológico y veterinario'],
            ['codigo' => '47722', 'valor' => 'Venta al por menor de productos cosméticos y de tocador'],
            ['codigo' => '47731', 'valor' => 'Venta al por menor de productos de joyería, bisutería, óptica, relojería'],
            ['codigo' => '47732', 'valor' => 'Venta al por menor de plantas, semillas, animales y artículos conexos'],
            ['codigo' => '47733', 'valor' => 'Venta al por menor de combustibles de uso doméstico (gas propano y gas licuado)'],
            ['codigo' => '47734', 'valor' => 'Venta al por menor de artesanías, artículos cerámicos y recuerdos en general'],
            ['codigo' => '47735', 'valor' => 'Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos religiosos en general'],
            ['codigo' => '47736', 'valor' => 'Venta al por menor de armas de fuego, municiones y accesorios'],
            ['codigo' => '47737', 'valor' => 'Venta al por menor de artículos de cohetería y pirotécnicos'],
            ['codigo' => '47738', 'valor' => 'Venta al por menor de artículos desechables de uso personal y doméstico (servilletas, papel higiénico, pañales, toallas sanitarias, etc.)'],
            ['codigo' => '47739', 'valor' => 'Venta al por menor de otros productos n.c.p.'],
            ['codigo' => '47741', 'valor' => 'Venta al por menor de artículos usados'],
            ['codigo' => '47742', 'valor' => 'Venta al por menor de textiles y confecciones usados'],
            ['codigo' => '47743', 'valor' => 'Venta al por menor de libros, revistas, papel y cartón usados'],
            ['codigo' => '47749', 'valor' => 'Venta al por menor de productos usados n.c.p.'],
            ['codigo' => '47811', 'valor' => 'Venta al por menor de frutas, verduras y hortalizas'],
            ['codigo' => '47812', 'valor' => 'Venta al por menor de carnes, embutidos y productos de granja'],
            ['codigo' => '47814', 'valor' => 'Venta al por menor de productos lácteos'],
            ['codigo' => '47815', 'valor' => 'Venta al por menor de productos de panadería, galletas y similares'],
            ['codigo' => '47816', 'valor' => 'Venta al por menor de bebidas'],
            ['codigo' => '47818', 'valor' => 'Venta al por menor en tiendas de mercado y puestos'],
            ['codigo' => '47821', 'valor' => 'Venta al por menor de hilados, tejidos y productos textiles de mercería en puestos de mercados y ferias'],
            ['codigo' => '47822', 'valor' => 'Venta al por menor de artículos textiles excepto confecciones para el hogar en puestos de mercados y ferias'],
            ['codigo' => '47823', 'valor' => 'Venta al por menor de confecciones textiles para el hogar en puestos de mercados y ferias'],
            ['codigo' => '47824', 'valor' => 'Venta al por menor de prendas de vestir, accesorios de vestir y similares en puestos de mercados y ferias'],
            ['codigo' => '47825', 'valor' => 'Venta al por menor de ropa usada'],
            ['codigo' => '47826', 'valor' => 'Venta al por menor de calzado, artículos de marroquinería y talabartería en puestos de mercados y ferias'],
            ['codigo' => '47827', 'valor' => 'Venta al por menor de artículos de marroquinería y talabartería en puestos de mercados y ferias'],
            ['codigo' => '47829', 'valor' => 'Venta al por menor de artículos textiles ncp en puestos de mercados y ferias'],
            ['codigo' => '47891', 'valor' => 'Venta al por menor de animales, flores y productos conexos en puestos de feria y mercados'],
            ['codigo' => '47892', 'valor' => 'Venta al por menor de productos medicinales, cosméticos, de tocador y de limpieza en puestos de ferias y mercados'],
            ['codigo' => '47893', 'valor' => 'Venta al por menor de artículos de bazar en puestos de ferias y mercados'],
            ['codigo' => '47894', 'valor' => 'Venta al por menor de artículos de papel, envases, libros, revistas y conexos en puestos de feria y mercados'],
            ['codigo' => '47895', 'valor' => 'Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de feria y mercados'],
            ['codigo' => '47896', 'valor' => 'Venta al por menor de equipos accesorios para las comunicaciones en puestos de feria y mercados'],
            ['codigo' => '47899', 'valor' => 'Venta al por menor en puestos de ferias y mercados n.c.p.'],
            ['codigo' => '47910', 'valor' => 'Venta al por menor por correo o Internet'],
            ['codigo' => '47990', 'valor' => 'Otros tipos de venta al por menor no realizada, en almacenes, puestos de venta o mercado'],
            ['codigo' => '49110', 'valor' => 'Transporte interurbano de pasajeros por ferrocarril'],
            ['codigo' => '49120', 'valor' => 'Transporte de carga por ferrocarril'],
            ['codigo' => '49211', 'valor' => 'Transporte de pasajeros urbanos e interurbano mediante buses'],
            ['codigo' => '49212', 'valor' => 'Transporte de pasajeros interdepartamental mediante microbuses'],
            ['codigo' => '49213', 'valor' => 'Transporte de pasajeros urbanos e interurbano mediante microbuses'],
            ['codigo' => '49214', 'valor' => 'Transporte de pasajeros interdepartamental mediante buses'],
            ['codigo' => '49221', 'valor' => 'Transporte internacional de pasajeros'],
            ['codigo' => '49222', 'valor' => 'Transporte de pasajeros mediante taxis y autos con chofer'],
            ['codigo' => '49223', 'valor' => 'Transporte escolar'],
            ['codigo' => '49225', 'valor' => 'Transporte de pasajeros para excursiones'],
            ['codigo' => '49226', 'valor' => 'Servicios de transporte de personal'],
            ['codigo' => '49229', 'valor' => 'Transporte de pasajeros por vía terrestre ncp'],
            ['codigo' => '49231', 'valor' => 'Transporte de carga urbano'],
            ['codigo' => '49232', 'valor' => 'Transporte nacional de carga'],
            ['codigo' => '49233', 'valor' => 'Transporte de carga internacional'],
            ['codigo' => '49234', 'valor' => 'Servicios de mudanza'],
            ['codigo' => '49235', 'valor' => 'Alquiler de vehículos de carga con conductor'],
            ['codigo' => '49300', 'valor' => 'Transporte por oleoducto o gasoducto'],
            ['codigo' => '50110', 'valor' => 'Transporte de pasajeros marítimo y de cabotaje'],
            ['codigo' => '50120', 'valor' => 'Transporte de carga marítimo y de cabotaje'],
            ['codigo' => '50211', 'valor' => 'Transporte de pasajeros por vías de navegación interiores'],
            ['codigo' => '50212', 'valor' => 'Alquiler de equipo de transporte de pasajeros por vías de navegación interior con conductor'],
            ['codigo' => '50220', 'valor' => 'Transporte de carga por vías de navegación interiores'],
            ['codigo' => '51100', 'valor' => 'Transporte aéreo de pasajeros'],
            ['codigo' => '51201', 'valor' => 'Transporte de carga por vía aérea'],
            ['codigo' => '51202', 'valor' => 'Alquiler de equipo de aerotransporte con operadores para el propósito de transportar carga'],
            ['codigo' => '52101', 'valor' => 'Alquiler de instalaciones de almacenamiento en zonas francas'],
            ['codigo' => '52102', 'valor' => 'Alquiler de silos para conservación y almacenamiento de granos'],
            ['codigo' => '52103', 'valor' => 'Alquiler de instalaciones con refrigeración para almacenamiento y conservación de alimentos y otros productos'],
            ['codigo' => '52109', 'valor' => 'Alquiler de bodegas para almacenamiento y depósito n.c.p.'],
            ['codigo' => '52211', 'valor' => 'Servicio de garaje y estacionamiento'],
            ['codigo' => '52212', 'valor' => 'Servicios de terminales para el transporte por vía terrestre'],
            ['codigo' => '52219', 'valor' => 'Servicios para el transporte por vía terrestre n.c.p.'],
            ['codigo' => '52220', 'valor' => 'Servicios para el transporte acuático'],
            ['codigo' => '52230', 'valor' => 'Servicios para el transporte aéreo'],
            ['codigo' => '52240', 'valor' => 'Manipulación de carga'],
            ['codigo' => '52290', 'valor' => 'Servicios para el transporte ncp'],
            ['codigo' => '52291', 'valor' => 'Agencias de tramitaciones aduanales'],
            ['codigo' => '53100', 'valor' => 'Servicios de correo nacional'],
            ['codigo' => '53200', 'valor' => 'Actividades de correo distintas a las actividades postales nacionales'],
            ['codigo' => '55101', 'valor' => 'Actividades de alojamiento para estancias cortas'],
            ['codigo' => '55102', 'valor' => 'Hoteles'],
            ['codigo' => '55200', 'valor' => 'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas'],
            ['codigo' => '55900', 'valor' => 'Alojamiento n.c.p.'],
            ['codigo' => '56101', 'valor' => 'Restaurantes'],
            ['codigo' => '56106', 'valor' => 'Pupusería'],
            ['codigo' => '56107', 'valor' => 'Actividades varias de restaurantes'],
            ['codigo' => '56108', 'valor' => 'Comedores'],
            ['codigo' => '56109', 'valor' => 'Merenderos ambulantes'],
            ['codigo' => '56210', 'valor' => 'Preparación de comida para eventos especiales'],
            ['codigo' => '56291', 'valor' => 'Servicios de provisión de comidas por contrato'],
            ['codigo' => '56292', 'valor' => 'Servicios de concesión de cafetines y chalet en empresas e instituciones'],
            ['codigo' => '56299', 'valor' => 'Servicios de preparación de comidas ncp'],
            ['codigo' => '56301', 'valor' => 'Servicio de expendio de bebidas en salones y bares'],
            ['codigo' => '56302', 'valor' => 'Servicio de expendio de bebidas en puestos callejeros, mercados y ferias'],
            ['codigo' => '58110', 'valor' => 'Edición de libros, folletos, partituras y otras ediciones distintas a estas'],
            ['codigo' => '58120', 'valor' => 'Edición de directorios y listas de correos'],
            ['codigo' => '58130', 'valor' => 'Edición de periódicos, revistas y otras publicaciones periódicas'],
            ['codigo' => '58190', 'valor' => 'Otras actividades de edición'],
            ['codigo' => '58200', 'valor' => 'Edición de programas informáticos (software)'],
            ['codigo' => '59110', 'valor' => 'Actividades de producción cinematográfica'],
            ['codigo' => '59120', 'valor' => 'Actividades de post producción de películas, videos y programas de televisión'],
            ['codigo' => '59130', 'valor' => 'Actividades de distribución de películas cinematográficas, videos y programas de televisión'],
            ['codigo' => '59140', 'valor' => 'Actividades de exhibición de películas cinematográficas y cintas de vídeo'],
            ['codigo' => '59200', 'valor' => 'Actividades de edición y grabación de música'],
            ['codigo' => '60100', 'valor' => 'Servicios de difusiones de radio'],
            ['codigo' => '60201', 'valor' => 'Actividades de programación y difusión de televisión abierta'],
            ['codigo' => '60202', 'valor' => 'Actividades de suscripción y difusión de televisión por cable y/o suscripción'],
            ['codigo' => '60299', 'valor' => 'Servicios de televisión, incluye televisión por cable'],
            ['codigo' => '60900', 'valor' => 'Programación y transmisión de radio y televisión'],
            ['codigo' => '61101', 'valor' => 'Servicio de telefonía'],
            ['codigo' => '61102', 'valor' => 'Servicio de Internet'],
            ['codigo' => '61103', 'valor' => 'Servicio de telefonía fija'],
            ['codigo' => '61109', 'valor' => 'Servicio de Internet n.c.p.'],
            ['codigo' => '61201', 'valor' => 'Servicios de telefonía celular'],
            ['codigo' => '61202', 'valor' => 'Servicios de Internet inalámbrico'],
            ['codigo' => '61209', 'valor' => 'Servicios de telecomunicaciones inalámbrico n.c.p.'],
            ['codigo' => '61301', 'valor' => 'Telecomunicaciones satelitales'],
            ['codigo' => '61309', 'valor' => 'Comunicación vía satélite n.c.p.'],
            ['codigo' => '61900', 'valor' => 'Actividades de telecomunicación n.c.p.'],
            ['codigo' => '62010', 'valor' => 'Programación Informática'],
            ['codigo' => '62020', 'valor' => 'Consultorías y gestión de servicios informáticos'],
            ['codigo' => '62090', 'valor' => 'Otras actividades de tecnología de información y servicios de computadora'],
            ['codigo' => '63110', 'valor' => 'Procesamiento de datos y actividades relacionadas'],
            ['codigo' => '63120', 'valor' => 'Portales WEB'],
            ['codigo' => '63910', 'valor' => 'Servicios de Agencias de Noticias'],
            ['codigo' => '63990', 'valor' => 'Otros servicios de información n.c.p.'],
            ['codigo' => '64110', 'valor' => 'Servicios provistos por el Banco Central de El Salvador'],
            ['codigo' => '64190', 'valor' => 'Bancos'],
            ['codigo' => '64192', 'valor' => 'Entidades dedicadas al envío de remesas'],
            ['codigo' => '64199', 'valor' => 'Otras entidades financieras'],
            ['codigo' => '64200', 'valor' => 'Actividades de sociedades de cartera'],
            ['codigo' => '64300', 'valor' => 'Fideicomisos, fondos y otras fuentes de financiamiento'],
            ['codigo' => '64910', 'valor' => 'Arrendamientos financieros'],
            ['codigo' => '64920', 'valor' => 'Asociaciones cooperativas de ahorro y crédito dedicadas a la intermediación financiera'],
            ['codigo' => '64921', 'valor' => 'Instituciones emisoras de tarjetas de crédito y otros'],
            ['codigo' => '64922', 'valor' => 'Tipos de crédito ncp'],
            ['codigo' => '64928', 'valor' => 'Prestamistas y casas de empeño'],
            ['codigo' => '64990', 'valor' => 'Actividades de servicios financieros, excepto la financiación de planes de seguros y de pensiones n.c.p.'],
            ['codigo' => '65110', 'valor' => 'Planes de seguros de vida'],
            ['codigo' => '65120', 'valor' => 'Planes de seguro excepto de vida'],
            ['codigo' => '65199', 'valor' => 'Seguros generales de todo tipo'],
            ['codigo' => '65200', 'valor' => 'Planes de seguro'],
            ['codigo' => '65300', 'valor' => 'Planes de pensiones'],
            ['codigo' => '66110', 'valor' => 'Administración de mercados financieros (Bolsa de Valores)'],
            ['codigo' => '66120', 'valor' => 'Actividades bursátiles (Corredores de Bolsa)'],
            ['codigo' => '66190', 'valor' => 'Actividades auxiliares de la intermediación financiera ncp'],
            ['codigo' => '66210', 'valor' => 'Evaluación de riesgos y daños'],
            ['codigo' => '66220', 'valor' => 'Actividades de agentes y corredores de seguros'],
            ['codigo' => '66290', 'valor' => 'Otras actividades auxiliares de seguros y fondos de pensiones'],
            ['codigo' => '66300', 'valor' => 'Actividades de administración de fondos'],
            ['codigo' => '68101', 'valor' => 'Servicio de alquiler y venta de lotes en cementerios'],
            ['codigo' => '68109', 'valor' => 'Actividades inmobiliarias realizadas con bienes propios o arrendados n.c.p.'],
            ['codigo' => '68200', 'valor' => 'Actividades Inmobiliarias Realizadas a Cambio de una Retribución o por Contrata'],
            ['codigo' => '69100', 'valor' => 'Actividades jurídicas'],
            ['codigo' => '69200', 'valor' => 'Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos'],
            ['codigo' => '70100', 'valor' => 'Actividades de oficinas centrales de sociedades de cartera'],
            ['codigo' => '70200', 'valor' => 'Actividades de consultoría en gestión empresarial'],
            ['codigo' => '71101', 'valor' => 'Servicios de arquitectura y planificación urbana y servicios conexos'],
            ['codigo' => '71102', 'valor' => 'Servicios de ingeniería'],
            ['codigo' => '71103', 'valor' => 'Servicios de agrimensura, topografía, cartografía, prospección y geofísica y servicios conexos'],
            ['codigo' => '71200', 'valor' => 'Ensayos y análisis técnicos'],
            ['codigo' => '72100', 'valor' => 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería'],
            ['codigo' => '72199', 'valor' => 'Investigaciones científicas'],
            ['codigo' => '72200', 'valor' => 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades científica y desarrollo'],
            ['codigo' => '73100', 'valor' => 'Publicidad'],
            ['codigo' => '73200', 'valor' => 'Investigación de mercados y realización de encuestas de opinión pública'],
            ['codigo' => '74100', 'valor' => 'Actividades de diseño especializado'],
            ['codigo' => '74200', 'valor' => 'Actividades de fotografía'],
            ['codigo' => '74900', 'valor' => 'Servicios profesionales y científicos ncp'],
            ['codigo' => '75000', 'valor' => 'Actividades veterinarias'],
            ['codigo' => '77101', 'valor' => 'Alquiler de equipo de transporte terrestre'],
            ['codigo' => '77102', 'valor' => 'Alquiler de equipo de transporte acuático'],
            ['codigo' => '77103', 'valor' => 'Alquiler de equipo de transporte por vía aérea'],
            ['codigo' => '77210', 'valor' => 'Alquiler y arrendamiento de equipo de recreo y deportivo'],
            ['codigo' => '77220', 'valor' => 'Alquiler de cintas de video y discos'],
            ['codigo' => '77290', 'valor' => 'Alquiler de otros efectos personales y enseres domésticos'],
            ['codigo' => '77300', 'valor' => 'Alquiler de maquinaria y equipo'],
            ['codigo' => '77400', 'valor' => 'Arrendamiento de productos de propiedad intelectual'],
            ['codigo' => '78100', 'valor' => 'Obtención y dotación de personal'],
            ['codigo' => '78200', 'valor' => 'Actividades de las agencias de trabajo temporal'],
            ['codigo' => '78300', 'valor' => 'Dotación de recursos humanos y gestión; gestión de las funciones de recursos humanos'],
            ['codigo' => '79110', 'valor' => 'Actividades de agencias de viajes y organizadores de viajes; actividades de asistencia a turistas'],
            ['codigo' => '79120', 'valor' => 'Actividades de los operadores turísticos'],
            ['codigo' => '79900', 'valor' => 'Otros servicios de reservas y actividades relacionadas'],
            ['codigo' => '80100', 'valor' => 'Servicios de seguridad privados'],
            ['codigo' => '80201', 'valor' => 'Actividades de servicios de sistemas de seguridad'],
            ['codigo' => '80202', 'valor' => 'Actividades para la prestación de sistemas de seguridad'],
            ['codigo' => '80300', 'valor' => 'Actividades de investigación'],
            ['codigo' => '81100', 'valor' => 'Actividades combinadas de mantenimiento de edificios e instalaciones'],
            ['codigo' => '81210', 'valor' => 'Limpieza general de edificios'],
            ['codigo' => '81290', 'valor' => 'Otras actividades combinadas de mantenimiento de edificios e instalaciones ncp'],
            ['codigo' => '81300', 'valor' => 'Servicio de jardinería'],
            ['codigo' => '82110', 'valor' => 'Servicios administrativos de oficinas'],
            ['codigo' => '82190', 'valor' => 'Servicio de fotocopiado y similares, excepto en imprentas'],
            ['codigo' => '82200', 'valor' => 'Actividades de las centrales de llamadas (call center)'],
            ['codigo' => '82300', 'valor' => 'Organización de convenciones y ferias de negocios'],
            ['codigo' => '82910', 'valor' => 'Actividades de agencias de cobro y oficinas de crédito'],
            ['codigo' => '82921', 'valor' => 'Servicios de envase y empaque de productos alimenticios'],
            ['codigo' => '82922', 'valor' => 'Servicios de envase y empaque de productos medicinales'],
            ['codigo' => '82929', 'valor' => 'Servicio de envase y empaque ncp'],
            ['codigo' => '82990', 'valor' => 'Actividades de apoyo empresariales ncp'],
            ['codigo' => '84110', 'valor' => 'Actividades de la Administración Pública en general'],
            ['codigo' => '84111', 'valor' => 'Alcaldías Municipales'],
            ['codigo' => '84120', 'valor' => 'Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad social'],
            ['codigo' => '84130', 'valor' => 'Regulación y facilitación de la actividad económica'],
            ['codigo' => '84210', 'valor' => 'Actividades de administración y funcionamiento del Ministerio de Relaciones Exteriores'],
            ['codigo' => '84220', 'valor' => 'Actividades de defensa'],
            ['codigo' => '84230', 'valor' => 'Actividades de mantenimiento del orden público y de seguridad'],
            ['codigo' => '84300', 'valor' => 'Actividades de planes de seguridad social de afiliación obligatoria'],
            ['codigo' => '85101', 'valor' => 'Guardería educativa'],
            ['codigo' => '85102', 'valor' => 'Enseñanza preescolar o parvularia'],
            ['codigo' => '85103', 'valor' => 'Enseñanza primaria'],
            ['codigo' => '85104', 'valor' => 'Servicio de educación preescolar y primaria integrada'],
            ['codigo' => '85211', 'valor' => 'Enseñanza secundaria tercer ciclo (7°, 8° y 9°)'],
            ['codigo' => '85212', 'valor' => 'Enseñanza secundaria de formación general bachillerato'],
            ['codigo' => '85221', 'valor' => 'Enseñanza secundaria de formación técnica y profesional'],
            ['codigo' => '85222', 'valor' => 'Enseñanza secundaria de formación técnica y profesional integrada con enseñanza primaria'],
            ['codigo' => '85301', 'valor' => 'Enseñanza superior universitaria'],
            ['codigo' => '85302', 'valor' => 'Enseñanza superior no universitaria'],
            ['codigo' => '85303', 'valor' => 'Enseñanza superior integrada a educación secundaria y/o primaria'],
            ['codigo' => '85410', 'valor' => 'Educación deportiva y recreativa'],
            ['codigo' => '85420', 'valor' => 'Educación cultural'],
            ['codigo' => '85490', 'valor' => 'Otros tipos de enseñanza n.c.p.'],
            ['codigo' => '85499', 'valor' => 'Enseñanza formal'],
            ['codigo' => '85500', 'valor' => 'Servicios de apoyo a la enseñanza'],
            ['codigo' => '86100', 'valor' => 'Actividades de hospitales'],
            ['codigo' => '86201', 'valor' => 'Clínicas médicas'],
            ['codigo' => '86202', 'valor' => 'Servicios de Odontología'],
            ['codigo' => '86203', 'valor' => 'Servicios médicos'],
            ['codigo' => '86901', 'valor' => 'Servicios de análisis y estudios de diagnóstico'],
            ['codigo' => '86902', 'valor' => 'Actividades de atención de la salud humana'],
            ['codigo' => '86909', 'valor' => 'Otros servicios relacionados con la salud ncp'],
            ['codigo' => '87100', 'valor' => 'Residencias de ancianos con atención de enfermería'],
            ['codigo' => '87200', 'valor' => 'Instituciones dedicadas al tratamiento del retraso mental, problemas de salud mental y el uso indebido de sustancias nocivas'],
            ['codigo' => '87300', 'valor' => 'Instituciones dedicadas al cuidado de ancianos y discapacitados'],
            ['codigo' => '87900', 'valor' => 'Actividades de asistencia a niños y jóvenes'],
            ['codigo' => '87901', 'valor' => 'Otras actividades de atención en instituciones'],
            ['codigo' => '88100', 'valor' => 'Actividades de asistencia sociales sin alojamiento para ancianos y discapacitados'],
            ['codigo' => '88900', 'valor' => 'Servicios sociales sin alojamiento ncp'],
            ['codigo' => '90000', 'valor' => 'Actividades creativas artísticas y de esparcimiento'],
            ['codigo' => '91010', 'valor' => 'Actividades de bibliotecas y archivos'],
            ['codigo' => '91020', 'valor' => 'Actividades de museos y preservación de lugares y edificios históricos'],
            ['codigo' => '91030', 'valor' => 'Actividades de jardines botánicos, zoológicos y de reservas naturales'],
            ['codigo' => '92000', 'valor' => 'Actividades de juegos y apuestas'],
            ['codigo' => '93110', 'valor' => 'Gestión de instalaciones deportivas'],
            ['codigo' => '93120', 'valor' => 'Actividades de clubes deportivos'],
            ['codigo' => '93190', 'valor' => 'Otras actividades deportivas'],
            ['codigo' => '93210', 'valor' => 'Actividades de parques de atracciones y parques temáticos'],
            ['codigo' => '93291', 'valor' => 'Discotecas y salas de baile'],
            ['codigo' => '93298', 'valor' => 'Centros vacacionales'],
            ['codigo' => '93299', 'valor' => 'Actividades de esparcimiento ncp'],
            ['codigo' => '94110', 'valor' => 'Actividades de organizaciones empresariales y de empleadores'],
            ['codigo' => '94120', 'valor' => 'Actividades de organizaciones profesionales'],
            ['codigo' => '94200', 'valor' => 'Actividades de sindicatos'],
            ['codigo' => '94910', 'valor' => 'Actividades de organizaciones religiosas'],
            ['codigo' => '94920', 'valor' => 'Actividades de organizaciones políticas'],
            ['codigo' => '94990', 'valor' => 'Actividades de asociaciones n.c.p.'],
            ['codigo' => '95110', 'valor' => 'Reparación de computadoras y equipo periférico'],
            ['codigo' => '95120', 'valor' => 'Reparación de equipo de comunicación'],
            ['codigo' => '95210', 'valor' => 'Reparación de aparatos electrónicos de consumo'],
            ['codigo' => '95220', 'valor' => 'Reparación de aparatos domésticos y equipo de hogar y jardín'],
            ['codigo' => '95230', 'valor' => 'Reparación de calzado y artículos de cuero'],
            ['codigo' => '95240', 'valor' => 'Reparación de muebles y accesorios para el hogar'],
            ['codigo' => '95291', 'valor' => 'Reparación de instrumentos musicales'],
            ['codigo' => '95292', 'valor' => 'Servicios de cerrajería y copiado de llaves'],
            ['codigo' => '95293', 'valor' => 'Reparación de joyas y relojes'],
            ['codigo' => '95294', 'valor' => 'Reparación de bicicletas, sillas de ruedas y rodados n.c.p.'],
            ['codigo' => '95299', 'valor' => 'Reparaciones de enseres personales n.c.p.'],
            ['codigo' => '96010', 'valor' => 'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco'],
            ['codigo' => '96020', 'valor' => 'Peluquería y otros tratamientos de belleza'],
            ['codigo' => '96030', 'valor' => 'Pompas fúnebres y actividades conexas'],
            ['codigo' => '96091', 'valor' => 'Servicios de sauna y otros servicios para la estética corporal n.c.p.'],
            ['codigo' => '96092', 'valor' => 'Servicios n.c.p.'],
            ['codigo' => '97000', 'valor' => 'Actividad de los hogares en calidad de empleadores de personal doméstico'],
            ['codigo' => '98100', 'valor' => 'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio'],
            ['codigo' => '98200', 'valor' => 'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio'],
            ['codigo' => '99000', 'valor' => 'Actividades de organizaciones y órganos extraterritoriales']
        ]);
    }
}
